# Generated by Django 5.1.4 on 2025-01-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_adminreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=40)),
                ('admin_email', models.CharField(max_length=50)),
                ('admin_pass', models.CharField(max_length=40)),
            ],
        ),
    ]
