# Generated by Django 5.1.4 on 2025-02-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=40)),
            ],
        ),
    ]
