# Generated by Django 5.1.7 on 2025-03-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_level',
            name='time_limit',
            field=models.IntegerField(default=30, null=True),
        ),
    ]
