# Generated by Django 5.1.4 on 2025-02-07 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_alter_tbl_master_master_proof'),
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_question',
            name='master_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_master'),
        ),
    ]
