# Generated by Django 5.1.4 on 2025-02-08 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0007_tbl_level'),
        ('Guest', '0004_alter_tbl_master_master_proof'),
        ('Master', '0003_delete_tbl_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=100)),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_level')),
                ('master_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_master')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_questionanswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionanswer_option', models.CharField(max_length=40)),
                ('questionanswer_correct', models.CharField(max_length=40)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.tbl_question')),
            ],
        ),
    ]
