# Generated by Django 5.1.4 on 2025-01-25 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40)),
                ('user_contact', models.CharField(max_length=10)),
                ('user_email', models.CharField(max_length=40)),
                ('user_pass', models.CharField(max_length=10)),
                ('user_address', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='Assest/File/User')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
