# Generated by Django 5.1.4 on 2025-02-06 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
        ('Guest', '0002_alter_tbl_user_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(max_length=40)),
                ('master_contact', models.CharField(max_length=10)),
                ('master_email', models.CharField(max_length=40)),
                ('master_pass', models.CharField(max_length=10)),
                ('master_address', models.CharField(max_length=50)),
                ('master_proof', models.CharField(max_length=50)),
                ('master_photo', models.FileField(upload_to='Assest/File/master/')),
                ('master_vstatus', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
