# Generated by Django 5.1.4 on 2025-02-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_master',
            name='master_proof',
            field=models.FileField(upload_to='Assest/File/master/'),
        ),
    ]
