# Generated by Django 5.1.4 on 2025-02-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaints',
        ),
    ]
