# Generated by Django 5.1.4 on 2025-02-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_tbl_questionhead'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_questionhead',
        ),
    ]
