# Generated by Django 5.1.4 on 2025-02-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_tbl_questionhead'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaints',
        ),
    ]
