# Generated by Django 5.1.4 on 2025-02-15 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0004_alter_tbl_master_master_proof'),
        ('User', '0012_remove_tbl_feedback_master_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=40)),
                ('conplaint_content', models.CharField(max_length=100)),
                ('complaint_reply', models.CharField(max_length=100, null=True)),
                ('complaint_stautus', models.IntegerField(default=0)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_master')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_title', models.CharField(max_length=40)),
                ('feedback_content', models.CharField(max_length=100)),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_master')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_questionhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionhead_date', models.DateField(auto_now_add=True)),
                ('questionhead_status', models.IntegerField(default=0)),
                ('questionhead_code', models.CharField(max_length=40, null=True)),
                ('questionhead_level', models.CharField(max_length=40)),
                ('questionhead_subject', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
