# Generated by Django 5.1.4 on 2025-02-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
    ]
