# Generated by Django 5.1.4 on 2025-03-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_tbl_questionbody_tbl_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_useranswer',
            name='questionbody_id',
        ),
        migrations.RemoveField(
            model_name='tbl_useranswer',
            name='questionanswer_id',
        ),
        migrations.RemoveField(
            model_name='tbl_useranswer',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='tbl_questionbody',
        ),
        migrations.DeleteModel(
            name='tbl_useranswer',
        ),
    ]
