# Generated by Django 5.1.4 on 2025-03-14 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_alter_tbl_master_master_proof'),
        ('Master', '0004_initial'),
        ('User', '0017_remove_tbl_useranswer_questionbody_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_questionbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.tbl_question')),
                ('questionhead_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_questionhead')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_useranswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useranswer_starttime', models.IntegerField(default=0)),
                ('useranswer_endtime', models.IntegerField(default=0)),
                ('useranswer_mark', models.IntegerField(default=0)),
                ('questionanswer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.tbl_questionanswer')),
                ('questionbody_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_questionbody')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
