# Generated by Django 5.1.7 on 2025-03-16 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_level_time_limit'),
        ('Guest', '0004_alter_tbl_master_master_proof'),
        ('User', '0018_tbl_questionbody_tbl_useranswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer_starttime', models.IntegerField()),
                ('timer_currenttime', models.IntegerField()),
                ('timer_status', models.IntegerField(default=0)),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_level')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
