# Generated by Django 5.1.7 on 2025-03-17 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_level_time_limit'),
        ('User', '0019_tbl_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_questionhead',
            name='questionhead_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_level'),
        ),
        migrations.AlterField(
            model_name='tbl_questionhead',
            name='questionhead_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject'),
        ),
        migrations.DeleteModel(
            name='tbl_timer',
        ),
    ]
